// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "actionmapcollection1.h"

// Dispatch interfaces referenced by this interface
#include "ActionMap1.h"


/////////////////////////////////////////////////////////////////////////////
// CActionMapCollection1 properties

long CActionMapCollection1::GetCount()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

LPDISPATCH CActionMapCollection1::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x2, VT_DISPATCH, (void*)&result);
	return result;
}

/////////////////////////////////////////////////////////////////////////////
// CActionMapCollection1 operations

CActionMap1 CActionMapCollection1::Add(short Message, short Modifier, short KeyCode, short Action)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0x3, DISPATCH_METHOD, VT_DISPATCH, (void*)&pDispatch, parms,
		Message, Modifier, KeyCode, Action);
	return CActionMap1(pDispatch);
}

void CActionMapCollection1::Remove(short Message, short Modifier, short KeyCode)
{
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0x4, DISPATCH_METHOD, VT_EMPTY, NULL, parms,
		 Message, Modifier, KeyCode);
}

CActionMap1 CActionMapCollection1::GetItem(short Message, short Modifier, short KeyCode)
{
	LPDISPATCH pDispatch;
	static BYTE parms[] =
		VTS_I2 VTS_I2 VTS_I2;
	InvokeHelper(0x5, DISPATCH_PROPERTYGET, VT_DISPATCH, (void*)&pDispatch, parms,
		Message, Modifier, KeyCode);
	return CActionMap1(pDispatch);
}

void CActionMapCollection1::RemoveAll()
{
	InvokeHelper(0x6, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}

void CActionMapCollection1::Reset()
{
	InvokeHelper(0x7, DISPATCH_METHOD, VT_EMPTY, NULL, NULL);
}
