#if !defined(AFX_AXISCOLLECTION1_H__37CDF25A_B547_4D65_A137_F0FDFE7F92DA__INCLUDED_)
#define AFX_AXISCOLLECTION1_H__37CDF25A_B547_4D65_A137_F0FDFE7F92DA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CAxis1;

/////////////////////////////////////////////////////////////////////////////
// CAxisCollection1 wrapper class

class CAxisCollection1 : public COleDispatchDriver
{
public:
	CAxisCollection1() {}		// Calls COleDispatchDriver default constructor
	CAxisCollection1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAxisCollection1(const CAxisCollection1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	long GetCount();

// Operations
public:
	CAxis1 GetItem(const VARIANT& Index);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AXISCOLLECTION1_H__37CDF25A_B547_4D65_A137_F0FDFE7F92DA__INCLUDED_)
