#if !defined(AFX_AXIS1_H__8927A332_C7A7_4774_9373_BE84CE037AA7__INCLUDED_)
#define AFX_AXIS1_H__8927A332_C7A7_4774_9373_BE84CE037AA7__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CStrokeFont;
class CDerivedDouble1;
class CGridLines1;
class CValueLabelCollection1;
class CLabel1;

/////////////////////////////////////////////////////////////////////////////
// CAxis1 wrapper class

class CAxis1 : public COleDispatchDriver
{
public:
	CAxis1() {}		// Calls COleDispatchDriver default constructor
	CAxis1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CAxis1(const CAxis1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	CString GetName();
	BOOL GetIsShowing();
	void SetIsShowing(BOOL);
	long GetAnnotationMethod();
	void SetAnnotationMethod(long);
	double GetOrigin();
	void SetOrigin(double);
	CStrokeFont GetAnnotationFont();
	CStrokeFont GetTitleFont();
	CDerivedDouble1 GetMin();
	CDerivedDouble1 GetMax();
	CGridLines1 GetMajorGrid();
	CValueLabelCollection1 GetValueLabels();
	CLabel1 GetTitle();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_AXIS1_H__8927A332_C7A7_4774_9373_BE84CE037AA7__INCLUDED_)
