// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "axis1.h"

// Dispatch interfaces referenced by this interface
#include "strokefont.h"
#include "deriveddouble1.h"
#include "gridlines1.h"
#include "valuelabelcollection1.h"
#include "label1.h"


/////////////////////////////////////////////////////////////////////////////
// CAxis1 properties

LPDISPATCH CAxis1::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

CString CAxis1::GetName()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

BOOL CAxis1::GetIsShowing()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CAxis1::SetIsShowing(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

long CAxis1::GetAnnotationMethod()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CAxis1::SetAnnotationMethod(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

double CAxis1::GetOrigin()
{
	double result;
	GetProperty(0x5, VT_R8, (void*)&result);
	return result;
}

void CAxis1::SetOrigin(double propVal)
{
	SetProperty(0x5, VT_R8, propVal);
}

CStrokeFont CAxis1::GetAnnotationFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0x6, VT_DISPATCH, (void*)&pDispatch);
	return CStrokeFont(pDispatch);
}

CStrokeFont CAxis1::GetTitleFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0x7, VT_DISPATCH, (void*)&pDispatch);
	return CStrokeFont(pDispatch);
}

CDerivedDouble1 CAxis1::GetMin()
{
	LPDISPATCH pDispatch;
	GetProperty(0x8, VT_DISPATCH, (void*)&pDispatch);
	return CDerivedDouble1(pDispatch);
}

CDerivedDouble1 CAxis1::GetMax()
{
	LPDISPATCH pDispatch;
	GetProperty(0x9, VT_DISPATCH, (void*)&pDispatch);
	return CDerivedDouble1(pDispatch);
}

CGridLines1 CAxis1::GetMajorGrid()
{
	LPDISPATCH pDispatch;
	GetProperty(0xa, VT_DISPATCH, (void*)&pDispatch);
	return CGridLines1(pDispatch);
}

CValueLabelCollection1 CAxis1::GetValueLabels()
{
	LPDISPATCH pDispatch;
	GetProperty(0xb, VT_DISPATCH, (void*)&pDispatch);
	return CValueLabelCollection1(pDispatch);
}

CLabel1 CAxis1::GetTitle()
{
	LPDISPATCH pDispatch;
	GetProperty(0xc, VT_DISPATCH, (void*)&pDispatch);
	return CLabel1(pDispatch);
}

/////////////////////////////////////////////////////////////////////////////
// CAxis1 operations
