#if !defined(AFX_CEILING_H__CD403B0E_217C_4042_8DCB_B34CF2F6C620__INCLUDED_)
#define AFX_CEILING_H__CD403B0E_217C_4042_8DCB_B34CF2F6C620__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CProjection;

/////////////////////////////////////////////////////////////////////////////
// CCeiling wrapper class

class CCeiling : public COleDispatchDriver
{
public:
	CCeiling() {}		// Calls COleDispatchDriver default constructor
	CCeiling(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CCeiling(const CCeiling& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	CProjection GetProjection();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CEILING_H__CD403B0E_217C_4042_8DCB_B34CF2F6C620__INCLUDED_)
