#if !defined(AFX_CHART3DDATACOORDRESULT_H__79F772E3_F443_4A97_8951_F41D5D0538AF__INCLUDED_)
#define AFX_CHART3DDATACOORDRESULT_H__79F772E3_F443_4A97_8951_F41D5D0538AF__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CChart3DDataCoordResult wrapper class

class CChart3DDataCoordResult : public COleDispatchDriver
{
public:
	CChart3DDataCoordResult() {}		// Calls COleDispatchDriver default constructor
	CChart3DDataCoordResult(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CChart3DDataCoordResult(const CChart3DDataCoordResult& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetRegion();
	void SetRegion(long);
	double GetX();
	void SetX(double);
	double GetY();
	void SetY(double);
	double GetZ();
	void SetZ(double);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHART3DDATACOORDRESULT_H__79F772E3_F443_4A97_8951_F41D5D0538AF__INCLUDED_)
