// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "chartarea1.h"

// Dispatch interfaces referenced by this interface
#include "border1.h"
#include "location1.h"
#include "Interior1.h"
#include "viewport.h"
#include "plotcube.h"
#include "axiscollection1.h"
#include "View3D1.h"
#include "Surface.h"
#include "bar1.h"


/////////////////////////////////////////////////////////////////////////////
// CChartArea1 properties

CBorder1 CChartArea1::GetBorder()
{
	LPDISPATCH pDispatch;
	GetProperty(0x1, VT_DISPATCH, (void*)&pDispatch);
	return CBorder1(pDispatch);
}

CLocation1 CChartArea1::GetLocation()
{
	LPDISPATCH pDispatch;
	GetProperty(0x2, VT_DISPATCH, (void*)&pDispatch);
	return CLocation1(pDispatch);
}

CInterior1 CChartArea1::GetInterior()
{
	LPDISPATCH pDispatch;
	GetProperty(0x3, VT_DISPATCH, (void*)&pDispatch);
	return CInterior1(pDispatch);
}

LPDISPATCH CChartArea1::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x4, VT_DISPATCH, (void*)&result);
	return result;
}

CViewport CChartArea1::GetViewport()
{
	LPDISPATCH pDispatch;
	GetProperty(0x5, VT_DISPATCH, (void*)&pDispatch);
	return CViewport(pDispatch);
}

CPlotCube CChartArea1::GetPlotCube()
{
	LPDISPATCH pDispatch;
	GetProperty(0x6, VT_DISPATCH, (void*)&pDispatch);
	return CPlotCube(pDispatch);
}

CAxisCollection1 CChartArea1::GetAxes()
{
	LPDISPATCH pDispatch;
	GetProperty(0x7, VT_DISPATCH, (void*)&pDispatch);
	return CAxisCollection1(pDispatch);
}

CView3D1 CChartArea1::GetView3D()
{
	LPDISPATCH pDispatch;
	GetProperty(0x8, VT_DISPATCH, (void*)&pDispatch);
	return CView3D1(pDispatch);
}

CSurface CChartArea1::GetSurface()
{
	LPDISPATCH pDispatch;
	GetProperty(0x9, VT_DISPATCH, (void*)&pDispatch);
	return CSurface(pDispatch);
}

CBar1 CChartArea1::GetBar()
{
	LPDISPATCH pDispatch;
	GetProperty(0xa, VT_DISPATCH, (void*)&pDispatch);
	return CBar1(pDispatch);
}

/////////////////////////////////////////////////////////////////////////////
// CChartArea1 operations
