// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "chart3ddatacoordresult.h"


/////////////////////////////////////////////////////////////////////////////
// CChart3DDataCoordResult properties

long CChart3DDataCoordResult::GetRegion()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CChart3DDataCoordResult::SetRegion(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

double CChart3DDataCoordResult::GetX()
{
	double result;
	GetProperty(0x2, VT_R8, (void*)&result);
	return result;
}

void CChart3DDataCoordResult::SetX(double propVal)
{
	SetProperty(0x2, VT_R8, propVal);
}

double CChart3DDataCoordResult::GetY()
{
	double result;
	GetProperty(0x3, VT_R8, (void*)&result);
	return result;
}

void CChart3DDataCoordResult::SetY(double propVal)
{
	SetProperty(0x3, VT_R8, propVal);
}

double CChart3DDataCoordResult::GetZ()
{
	double result;
	GetProperty(0x4, VT_R8, (void*)&result);
	return result;
}

void CChart3DDataCoordResult::SetZ(double propVal)
{
	SetProperty(0x4, VT_R8, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CChart3DDataCoordResult operations
