// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "chart3ddataindexresult.h"


/////////////////////////////////////////////////////////////////////////////
// CChart3DDataIndexResult properties

long CChart3DDataIndexResult::GetRegion()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CChart3DDataIndexResult::SetRegion(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

long CChart3DDataIndexResult::GetRow()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CChart3DDataIndexResult::SetRow(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

long CChart3DDataIndexResult::GetColumn()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CChart3DDataIndexResult::SetColumn(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

long CChart3DDataIndexResult::GetDistance()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CChart3DDataIndexResult::SetDistance(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CChart3DDataIndexResult operations
