#if !defined(AFX_CHART3D_H__062BC45B_8331_496A_A094_4ACDFBF2FA60__INCLUDED_)
#define AFX_CHART3D_H__062BC45B_8331_496A_A094_4ACDFBF2FA60__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CTitle1;
class CLegend1;
class CBorder1;
class CInterior1;
class CChartArea1;
class CChartGroupCollection1;
class CChartLabelCollection1;
class CActionMapCollection1;

/////////////////////////////////////////////////////////////////////////////
// CChart3D wrapper class

class CChart3D : public CWnd
{
protected:
	DECLARE_DYNCREATE(CChart3D)
public:
	CLSID const& GetClsid()
	{
		static CLSID const clsid
			= { 0xca888f03, 0x45f5, 0x11cf, { 0x80, 0xb2, 0x0, 0x20, 0xaf, 0x19, 0xee, 0x14 } };
		return clsid;
	}
	virtual BOOL Create(LPCTSTR lpszClassName,
		LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect,
		CWnd* pParentWnd, UINT nID,
		CCreateContext* pContext = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID); }

    BOOL Create(LPCTSTR lpszWindowName, DWORD dwStyle,
		const RECT& rect, CWnd* pParentWnd, UINT nID,
		CFile* pPersist = NULL, BOOL bStorage = FALSE,
		BSTR bstrLicKey = NULL)
	{ return CreateControl(GetClsid(), lpszWindowName, dwStyle, rect, pParentWnd, nID,
		pPersist, bStorage, bstrLicKey); }

// Attributes
public:
	BOOL GetIsDoubleBuffered();
	void SetIsDoubleBuffered(BOOL);
	CTitle1 GetHeader();
	CTitle1 GetFooter();
	CLegend1 GetLegend();
	CBorder1 GetBorder();
	CInterior1 GetInterior();
	CChartArea1 GetChartArea();
	CChartGroupCollection1 GetChartGroups();
	long GetErrorOffset();
	void SetErrorOffset(long);
	CChartLabelCollection1 GetChartLabels();
	CActionMapCollection1 GetActionMaps();
	long GetPreviewMethod();
	void SetPreviewMethod(long);
	OLE_HANDLE GetHWnd();
	void SetHWnd(OLE_HANDLE);
	BOOL GetAllowUserChanges();
	void SetAllowUserChanges(BOOL);
	CString GetDataPath();
	void SetDataPath(LPCTSTR);

// Operations
public:
	void Refresh();
	BOOL Load(LPCTSTR FileName);
	BOOL Save(LPCTSTR FileName);
	void CallAction(long Action, long XCoord, long YCoord);
	BOOL DrawToDC(long Hdc, long Format, long Scale, long Left, long Top, long Width, long Height);
	BOOL PrintChart(long Format, long Scale, long Left, long Top, long Width, long Height);
	BOOL CopyToClipboard(long Format);
	BOOL DrawToFile(LPCTSTR FileName, long Format);
	BOOL ShowChartEditorElement(short Element, BOOL Show);
	BOOL IsChartEditorElementVisible(short Element);
	BOOL LoadURL(LPCTSTR URLName);
	void AboutBox();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHART3D_H__062BC45B_8331_496A_A094_4ACDFBF2FA60__INCLUDED_)
