#if !defined(AFX_CHART3DDATAINDEXRESULT_H__E1FF54BB_12E7_43C4_8952_E0E17B71DCDA__INCLUDED_)
#define AFX_CHART3DDATAINDEXRESULT_H__E1FF54BB_12E7_43C4_8952_E0E17B71DCDA__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CChart3DDataIndexResult wrapper class

class CChart3DDataIndexResult : public COleDispatchDriver
{
public:
	CChart3DDataIndexResult() {}		// Calls COleDispatchDriver default constructor
	CChart3DDataIndexResult(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CChart3DDataIndexResult(const CChart3DDataIndexResult& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetRegion();
	void SetRegion(long);
	long GetRow();
	void SetRow(long);
	long GetColumn();
	void SetColumn(long);
	long GetDistance();
	void SetDistance(long);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHART3DDATAINDEXRESULT_H__E1FF54BB_12E7_43C4_8952_E0E17B71DCDA__INCLUDED_)
