#if !defined(AFX_CHARTLABEL1_H__82AD737F_CAA0_4477_8D18_CAD9CE499134__INCLUDED_)
#define AFX_CHARTLABEL1_H__82AD737F_CAA0_4477_8D18_CAD9CE499134__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CBorder1;
class CInterior1;
class CStrokeFont;
class CCoord1;
class CDataCoord1;
class CDataIndex1;
class COleFont;
class CLabel1;

/////////////////////////////////////////////////////////////////////////////
// CChartLabel1 wrapper class

class CChartLabel1 : public COleDispatchDriver
{
public:
	CChartLabel1() {}		// Calls COleDispatchDriver default constructor
	CChartLabel1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CChartLabel1(const CChartLabel1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	CString GetName();
	void SetName(LPCTSTR);
	BOOL GetIsShowing();
	void SetIsShowing(BOOL);
	BOOL GetIsBatched();
	void SetIsBatched(BOOL);
	BOOL GetIsConnected();
	void SetIsConnected(BOOL);
	long GetAttachMethod();
	void SetAttachMethod(long);
	long GetAdjust();
	void SetAdjust(long);
	long GetPlane();
	void SetPlane(long);
	long GetHorizontalOffset();
	void SetHorizontalOffset(long);
	long GetVerticalOffset();
	void SetVerticalOffset(long);
	CBorder1 GetBorder();
	CInterior1 GetInterior();
	CStrokeFont GetStrokeFont();
	CCoord1 GetAttachCoord();
	CDataCoord1 GetAttachDataCoord();
	CDataIndex1 GetAttachDataIndex();
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	CLabel1 GetText();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHARTLABEL1_H__82AD737F_CAA0_4477_8D18_CAD9CE499134__INCLUDED_)
