#if !defined(AFX_CHART3DDATA_H__3F3F728B_D950_4DA7_B797_B39BC1BD6E7B__INCLUDED_)
#define AFX_CHART3DDATA_H__3F3F728B_D950_4DA7_B797_B39BC1BD6E7B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CChart3DData wrapper class

class CChart3DData : public COleDispatchDriver
{
public:
	CChart3DData() {}		// Calls COleDispatchDriver default constructor
	CChart3DData(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CChart3DData(const CChart3DData& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	BOOL GetIsBatched();
	void SetIsBatched(BOOL);
	BOOL GetIsSaved();
	void SetIsSaved(BOOL);
	CString GetFileName();
	void SetFileName(LPCTSTR);
	long GetLayout();
	void SetLayout(long);
	double GetHoleValue();
	void SetHoleValue(double);
	long GetRowCount();
	void SetRowCount(long);
	long GetColumnCount();
	void SetColumnCount(long);
	double GetRowOrigin();
	void SetRowOrigin(double);
	double GetColumnOrigin();
	void SetColumnOrigin(double);
	CString GetDataPath();
	void SetDataPath(LPCTSTR);

// Operations
public:
	double GetRowDelta(long Row);
	void SetRowDelta(long Row, double newValue);
	double GetColumnDelta(long Column);
	void SetColumnDelta(long Column, double newValue);
	double GetValue(long Row, long Column);
	void SetValue(long Row, long Column, double newValue);
	void Smooth(double Weight);
	CChart3DData Copy();
	CChart3DData CreateShaded(double Sweep, double Rise, double Scale, double Ambient, double Intensity);
	CChart3DData CreateSubset(double XStart, double YStart, double XEnd, double YEnd, long NumX, long NumY, long Method);
	BOOL Load(LPCTSTR FileName);
	BOOL Save(LPCTSTR FileName);
	BOOL CopyZArrayIn(const VARIANT& vArray);
	BOOL CopyZArrayOut(const VARIANT& vArray);
	long UpdateDataValue(double OldValue, double NewValue);
	BOOL LoadURL(LPCTSTR URLName);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHART3DDATA_H__3F3F728B_D950_4DA7_B797_B39BC1BD6E7B__INCLUDED_)
