// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "contour.h"

// Dispatch interfaces referenced by this interface
#include "ContourLevels.h"
#include "contourstylecollection.h"


/////////////////////////////////////////////////////////////////////////////
// CContour properties

LPDISPATCH CContour::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

BOOL CContour::GetIsContoured()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CContour::SetIsContoured(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL CContour::GetIsZoned()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CContour::SetIsZoned(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

long CContour::GetZoneMethod()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CContour::SetZoneMethod(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

CContourLevels CContour::GetLevels()
{
	LPDISPATCH pDispatch;
	GetProperty(0x5, VT_DISPATCH, (void*)&pDispatch);
	return CContourLevels(pDispatch);
}

CContourStyleCollection CContour::GetStyles()
{
	LPDISPATCH pDispatch;
	GetProperty(0x6, VT_DISPATCH, (void*)&pDispatch);
	return CContourStyleCollection(pDispatch);
}

/////////////////////////////////////////////////////////////////////////////
// CContour operations
