// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "datacoord1.h"


/////////////////////////////////////////////////////////////////////////////
// CDataCoord1 properties

LPDISPATCH CDataCoord1::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

double CDataCoord1::GetX()
{
	double result;
	GetProperty(0x2, VT_R8, (void*)&result);
	return result;
}

void CDataCoord1::SetX(double propVal)
{
	SetProperty(0x2, VT_R8, propVal);
}

double CDataCoord1::GetY()
{
	double result;
	GetProperty(0x3, VT_R8, (void*)&result);
	return result;
}

void CDataCoord1::SetY(double propVal)
{
	SetProperty(0x3, VT_R8, propVal);
}

double CDataCoord1::GetZ()
{
	double result;
	GetProperty(0x4, VT_R8, (void*)&result);
	return result;
}

void CDataCoord1::SetZ(double propVal)
{
	SetProperty(0x4, VT_R8, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CDataCoord1 operations
