#if !defined(AFX_DATAINDEX1_H__BE5AC17E_EAEA_4F8E_BE5C_CF89D3A00691__INCLUDED_)
#define AFX_DATAINDEX1_H__BE5AC17E_EAEA_4F8E_BE5C_CF89D3A00691__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDataIndex1 wrapper class

class CDataIndex1 : public COleDispatchDriver
{
public:
	CDataIndex1() {}		// Calls COleDispatchDriver default constructor
	CDataIndex1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDataIndex1(const CDataIndex1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	long GetRow();
	void SetRow(long);
	long GetColumn();
	void SetColumn(long);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DATAINDEX1_H__BE5AC17E_EAEA_4F8E_BE5C_CF89D3A00691__INCLUDED_)
