#if !defined(AFX_DATACOORD1_H__B15AE2F6_510C_47FB_A437_962FB5EF0214__INCLUDED_)
#define AFX_DATACOORD1_H__B15AE2F6_510C_47FB_A437_962FB5EF0214__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDataCoord1 wrapper class

class CDataCoord1 : public COleDispatchDriver
{
public:
	CDataCoord1() {}		// Calls COleDispatchDriver default constructor
	CDataCoord1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDataCoord1(const CDataCoord1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	double GetX();
	void SetX(double);
	double GetY();
	void SetY(double);
	double GetZ();
	void SetZ(double);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DATACOORD1_H__B15AE2F6_510C_47FB_A437_962FB5EF0214__INCLUDED_)
