// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "datacolor.h"

// Dispatch interfaces referenced by this interface
#include "DataIndex1.h"


/////////////////////////////////////////////////////////////////////////////
// CDataColor properties

LPDISPATCH CDataColor::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

unsigned long CDataColor::GetColor()
{
	unsigned long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CDataColor::SetColor(unsigned long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

CDataIndex1 CDataColor::GetDataIndex()
{
	LPDISPATCH pDispatch;
	GetProperty(0x3, VT_DISPATCH, (void*)&pDispatch);
	return CDataIndex1(pDispatch);
}

/////////////////////////////////////////////////////////////////////////////
// CDataColor operations
