// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "derivedlong1.h"


/////////////////////////////////////////////////////////////////////////////
// CDerivedLong1 properties

LPDISPATCH CDerivedLong1::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

long CDerivedLong1::GetValue()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CDerivedLong1::SetValue(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

BOOL CDerivedLong1::GetIsDefault()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CDerivedLong1::SetIsDefault(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CDerivedLong1 operations
