#if !defined(AFX_DERIVEDLONG1_H__58E51B4C_B686_4284_B308_4EB71E7DA19C__INCLUDED_)
#define AFX_DERIVEDLONG1_H__58E51B4C_B686_4284_B308_4EB71E7DA19C__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDerivedLong1 wrapper class

class CDerivedLong1 : public COleDispatchDriver
{
public:
	CDerivedLong1() {}		// Calls COleDispatchDriver default constructor
	CDerivedLong1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDerivedLong1(const CDerivedLong1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	long GetValue();
	void SetValue(long);
	BOOL GetIsDefault();
	void SetIsDefault(BOOL);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DERIVEDLONG1_H__58E51B4C_B686_4284_B308_4EB71E7DA19C__INCLUDED_)
