// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "fillstyle.h"


/////////////////////////////////////////////////////////////////////////////
// CFillStyle properties

long CFillStyle::GetPattern()
{
	long result;
	GetProperty(0x1, VT_I4, (void*)&result);
	return result;
}

void CFillStyle::SetPattern(long propVal)
{
	SetProperty(0x1, VT_I4, propVal);
}

unsigned long CFillStyle::GetColor()
{
	unsigned long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CFillStyle::SetColor(unsigned long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

LPDISPATCH CFillStyle::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x3, VT_DISPATCH, (void*)&result);
	return result;
}

/////////////////////////////////////////////////////////////////////////////
// CFillStyle operations
