// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "image1.h"


/////////////////////////////////////////////////////////////////////////////
// CImage1 properties

LPDISPATCH CImage1::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

CString CImage1::GetFileName()
{
	CString result;
	GetProperty(0x2, VT_BSTR, (void*)&result);
	return result;
}

void CImage1::SetFileName(LPCTSTR propVal)
{
	SetProperty(0x2, VT_BSTR, propVal);
}

long CImage1::GetLayout()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CImage1::SetLayout(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

BOOL CImage1::GetIsEmbedded()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CImage1::SetIsEmbedded(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CImage1 operations
