#if !defined(AFX_LABEL1_H__B4D0FC03_9A99_488F_9597_769693E9BCEE__INCLUDED_)
#define AFX_LABEL1_H__B4D0FC03_9A99_488F_9597_769693E9BCEE__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CLabel1 wrapper class

class CLabel1 : public COleDispatchDriver
{
public:
	CLabel1() {}		// Calls COleDispatchDriver default constructor
	CLabel1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLabel1(const CLabel1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	CString GetText();
	void SetText(LPCTSTR);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LABEL1_H__B4D0FC03_9A99_488F_9597_769693E9BCEE__INCLUDED_)
