// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "legend1.h"

// Dispatch interfaces referenced by this interface
#include "border1.h"
#include "location1.h"
#include "Interior1.h"
#include "font.h"
#include "LabelCollection1.h"


/////////////////////////////////////////////////////////////////////////////
// CLegend1 properties

LPDISPATCH CLegend1::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

long CLegend1::GetAnchor()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CLegend1::SetAnchor(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

long CLegend1::GetOrientation()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CLegend1::SetOrientation(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

BOOL CLegend1::GetIsShowing()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CLegend1::SetIsShowing(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

CBorder1 CLegend1::GetBorder()
{
	LPDISPATCH pDispatch;
	GetProperty(0x5, VT_DISPATCH, (void*)&pDispatch);
	return CBorder1(pDispatch);
}

CLocation1 CLegend1::GetLocation()
{
	LPDISPATCH pDispatch;
	GetProperty(0x6, VT_DISPATCH, (void*)&pDispatch);
	return CLocation1(pDispatch);
}

CInterior1 CLegend1::GetInterior()
{
	LPDISPATCH pDispatch;
	GetProperty(0x7, VT_DISPATCH, (void*)&pDispatch);
	return CInterior1(pDispatch);
}

long CLegend1::GetType()
{
	long result;
	GetProperty(0x8, VT_I4, (void*)&result);
	return result;
}

void CLegend1::SetType(long propVal)
{
	SetProperty(0x8, VT_I4, propVal);
}

COleFont CLegend1::GetFont()
{
	LPDISPATCH pDispatch;
	GetProperty(0x9, VT_DISPATCH, (void*)&pDispatch);
	return COleFont(pDispatch);
}

void CLegend1::SetFont(LPDISPATCH propVal)
{
	SetProperty(0x9, VT_DISPATCH, propVal);
}

CLabelCollection1 CLegend1::GetLabels()
{
	LPDISPATCH pDispatch;
	GetProperty(0xa, VT_DISPATCH, (void*)&pDispatch);
	return CLabelCollection1(pDispatch);
}

/////////////////////////////////////////////////////////////////////////////
// CLegend1 operations
