// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "linestyle1.h"


/////////////////////////////////////////////////////////////////////////////
// CLineStyle1 properties

LPDISPATCH CLineStyle1::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

long CLineStyle1::GetPattern()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CLineStyle1::SetPattern(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

unsigned long CLineStyle1::GetColor()
{
	unsigned long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CLineStyle1::SetColor(unsigned long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

long CLineStyle1::GetWidth()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CLineStyle1::SetWidth(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CLineStyle1 operations
