#if !defined(AFX_LINESTYLE1_H__862D13AD_AAF6_4564_B093_CA363B04A5D7__INCLUDED_)
#define AFX_LINESTYLE1_H__862D13AD_AAF6_4564_B093_CA363B04A5D7__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CLineStyle1 wrapper class

class CLineStyle1 : public COleDispatchDriver
{
public:
	CLineStyle1() {}		// Calls COleDispatchDriver default constructor
	CLineStyle1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLineStyle1(const CLineStyle1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	long GetPattern();
	void SetPattern(long);
	unsigned long GetColor();
	void SetColor(unsigned long);
	long GetWidth();
	void SetWidth(long);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LINESTYLE1_H__862D13AD_AAF6_4564_B093_CA363B04A5D7__INCLUDED_)
