#if !defined(AFX_LOCATION1_H__0580F3A8_CA12_4BC4_B9A8_EFE83F438C31__INCLUDED_)
#define AFX_LOCATION1_H__0580F3A8_CA12_4BC4_B9A8_EFE83F438C31__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CDerivedLong1;

/////////////////////////////////////////////////////////////////////////////
// CLocation1 wrapper class

class CLocation1 : public COleDispatchDriver
{
public:
	CLocation1() {}		// Calls COleDispatchDriver default constructor
	CLocation1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLocation1(const CLocation1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	CDerivedLong1 GetLeft();
	CDerivedLong1 GetTop();
	CDerivedLong1 GetWidth();
	CDerivedLong1 GetHeight();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LOCATION1_H__0580F3A8_CA12_4BC4_B9A8_EFE83F438C31__INCLUDED_)
