// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "location1.h"

// Dispatch interfaces referenced by this interface
#include "DerivedLong1.h"


/////////////////////////////////////////////////////////////////////////////
// CLocation1 properties

LPDISPATCH CLocation1::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

CDerivedLong1 CLocation1::GetLeft()
{
	LPDISPATCH pDispatch;
	GetProperty(0x2, VT_DISPATCH, (void*)&pDispatch);
	return CDerivedLong1(pDispatch);
}

CDerivedLong1 CLocation1::GetTop()
{
	LPDISPATCH pDispatch;
	GetProperty(0x3, VT_DISPATCH, (void*)&pDispatch);
	return CDerivedLong1(pDispatch);
}

CDerivedLong1 CLocation1::GetWidth()
{
	LPDISPATCH pDispatch;
	GetProperty(0x4, VT_DISPATCH, (void*)&pDispatch);
	return CDerivedLong1(pDispatch);
}

CDerivedLong1 CLocation1::GetHeight()
{
	LPDISPATCH pDispatch;
	GetProperty(0x5, VT_DISPATCH, (void*)&pDispatch);
	return CDerivedLong1(pDispatch);
}

/////////////////////////////////////////////////////////////////////////////
// CLocation1 operations
