#if !defined(AFX_PLOTCUBE_H__3C757240_25B6_4D48_8932_CAB991D995CB__INCLUDED_)
#define AFX_PLOTCUBE_H__3C757240_25B6_4D48_8932_CAB991D995CB__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CCeiling;
class CFloor;
class CInterior1;

/////////////////////////////////////////////////////////////////////////////
// CPlotCube wrapper class

class CPlotCube : public COleDispatchDriver
{
public:
	CPlotCube() {}		// Calls COleDispatchDriver default constructor
	CPlotCube(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CPlotCube(const CPlotCube& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	double GetXScale();
	void SetXScale(double);
	double GetYScale();
	void SetYScale(double);
	CCeiling GetCeiling();
	CFloor GetFloor();
	CInterior1 GetInterior();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PLOTCUBE_H__3C757240_25B6_4D48_8932_CAB991D995CB__INCLUDED_)
