#if !defined(AFX_PROJECTION_H__EF9B87B0_291E_4A89_AAB2_4E8FECECE8C7__INCLUDED_)
#define AFX_PROJECTION_H__EF9B87B0_291E_4A89_AAB2_4E8FECECE8C7__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CProjection wrapper class

class CProjection : public COleDispatchDriver
{
public:
	CProjection() {}		// Calls COleDispatchDriver default constructor
	CProjection(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CProjection(const CProjection& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	BOOL GetIsContoured();
	void SetIsContoured(BOOL);
	BOOL GetIsZoned();
	void SetIsZoned(BOOL);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_PROJECTION_H__EF9B87B0_291E_4A89_AAB2_4E8FECECE8C7__INCLUDED_)
