#if !defined(AFX_STROKEFONT_H__739C471F_3016_4DA0_9885_93965F773F01__INCLUDED_)
#define AFX_STROKEFONT_H__739C471F_3016_4DA0_9885_93965F773F01__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CStrokeFont wrapper class

class CStrokeFont : public COleDispatchDriver
{
public:
	CStrokeFont() {}		// Calls COleDispatchDriver default constructor
	CStrokeFont(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CStrokeFont(const CStrokeFont& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	long GetType();
	void SetType(long);
	long GetSize();
	void SetSize(long);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_STROKEFONT_H__739C471F_3016_4DA0_9885_93965F773F01__INCLUDED_)
