#if !defined(AFX_SURFACE_H__158C74F9_C0A8_424A_A676_B8FE76FB4EBE__INCLUDED_)
#define AFX_SURFACE_H__158C74F9_C0A8_424A_A676_B8FE76FB4EBE__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CSurface wrapper class

class CSurface : public COleDispatchDriver
{
public:
	CSurface() {}		// Calls COleDispatchDriver default constructor
	CSurface(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CSurface(const CSurface& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	BOOL GetIsSolid();
	void SetIsSolid(BOOL);
	BOOL GetIsRowMeshShowing();
	void SetIsRowMeshShowing(BOOL);
	BOOL GetIsColumnMeshShowing();
	void SetIsColumnMeshShowing(BOOL);
	long GetRowMeshFilter();
	void SetRowMeshFilter(long);
	long GetColumnMeshFilter();
	void SetColumnMeshFilter(long);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_SURFACE_H__158C74F9_C0A8_424A_A676_B8FE76FB4EBE__INCLUDED_)
