#if !defined(AFX_TITLE1_H__C9B038A6_5402_4525_B1B9_1D96E456E2AD__INCLUDED_)
#define AFX_TITLE1_H__C9B038A6_5402_4525_B1B9_1D96E456E2AD__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CBorder1;
class CInterior1;
class CLocation1;
class COleFont;
class CLabel1;

/////////////////////////////////////////////////////////////////////////////
// CTitle1 wrapper class

class CTitle1 : public COleDispatchDriver
{
public:
	CTitle1() {}		// Calls COleDispatchDriver default constructor
	CTitle1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CTitle1(const CTitle1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetAdjust();
	void SetAdjust(long);
	BOOL GetIsShowing();
	void SetIsShowing(BOOL);
	LPDISPATCH GetParent();
	CBorder1 GetBorder();
	CInterior1 GetInterior();
	CLocation1 GetLocation();
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	CLabel1 GetText();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_TITLE1_H__C9B038A6_5402_4525_B1B9_1D96E456E2AD__INCLUDED_)
