#if !defined(AFX_VALUELABELCOLLECTION1_H__57D09D29_09A3_4913_AAEE_F1603CD91331__INCLUDED_)
#define AFX_VALUELABELCOLLECTION1_H__57D09D29_09A3_4913_AAEE_F1603CD91331__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CValueLabel1;

/////////////////////////////////////////////////////////////////////////////
// CValueLabelCollection1 wrapper class

class CValueLabelCollection1 : public COleDispatchDriver
{
public:
	CValueLabelCollection1() {}		// Calls COleDispatchDriver default constructor
	CValueLabelCollection1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CValueLabelCollection1(const CValueLabelCollection1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	long GetCount();

// Operations
public:
	CValueLabel1 Add(double Value, LPCTSTR Text);
	void Remove(const VARIANT& Index);
	CValueLabel1 GetItem(const VARIANT& Index);
	void RemoveAll();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VALUELABELCOLLECTION1_H__57D09D29_09A3_4913_AAEE_F1603CD91331__INCLUDED_)
