#if !defined(AFX_VIEW3D1_H__0B0B5917_DD83_4DB1_AB28_807F4B8427FE__INCLUDED_)
#define AFX_VIEW3D1_H__0B0B5917_DD83_4DB1_AB28_807F4B8427FE__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CView3D1 wrapper class

class CView3D1 : public COleDispatchDriver
{
public:
	CView3D1() {}		// Calls COleDispatchDriver default constructor
	CView3D1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CView3D1(const CView3D1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	double GetPerspective();
	void SetPerspective(double);
	double GetXRotation();
	void SetXRotation(double);
	double GetYRotation();
	void SetYRotation(double);
	double GetZRotation();
	void SetZRotation(double);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VIEW3D1_H__0B0B5917_DD83_4DB1_AB28_807F4B8427FE__INCLUDED_)
