#if !defined(AFX_VIEWPORT_H__F71906DD_C475_4E7F_9CBA_8DE689693E24__INCLUDED_)
#define AFX_VIEWPORT_H__F71906DD_C475_4E7F_9CBA_8DE689693E24__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CViewport wrapper class

class CViewport : public COleDispatchDriver
{
public:
	CViewport() {}		// Calls COleDispatchDriver default constructor
	CViewport(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CViewport(const CViewport& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	BOOL GetIsNormalized();
	void SetIsNormalized(BOOL);
	double GetScaleFactor();
	void SetScaleFactor(double);
	double GetHorizontalShift();
	void SetHorizontalShift(double);
	double GetVerticalShift();
	void SetVerticalShift(double);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_VIEWPORT_H__F71906DD_C475_4E7F_9CBA_8DE689693E24__INCLUDED_)
