// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "actionmap1.h"


/////////////////////////////////////////////////////////////////////////////
// CActionMap1 properties

short CActionMap1::GetMessage()
{
	short result;
	GetProperty(0x1, VT_I2, (void*)&result);
	return result;
}

short CActionMap1::GetModifier()
{
	short result;
	GetProperty(0x2, VT_I2, (void*)&result);
	return result;
}

short CActionMap1::GetKeyCode()
{
	short result;
	GetProperty(0x3, VT_I2, (void*)&result);
	return result;
}

short CActionMap1::GetAction()
{
	short result;
	GetProperty(0x4, VT_I2, (void*)&result);
	return result;
}

void CActionMap1::SetAction(short propVal)
{
	SetProperty(0x4, VT_I2, propVal);
}

LPDISPATCH CActionMap1::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x5, VT_DISPATCH, (void*)&result);
	return result;
}

/////////////////////////////////////////////////////////////////////////////
// CActionMap1 operations
