#if !defined(AFX_BAR1_H__21A6CC87_9310_4E1F_868D_A52BE20F7016__INCLUDED_)
#define AFX_BAR1_H__21A6CC87_9310_4E1F_868D_A52BE20F7016__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CDataColorCollection;

/////////////////////////////////////////////////////////////////////////////
// CBar1 wrapper class

class CBar1 : public COleDispatchDriver
{
public:
	CBar1() {}		// Calls COleDispatchDriver default constructor
	CBar1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CBar1(const CBar1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	long GetRowFormat();
	void SetRowFormat(long);
	double GetRowSpacing();
	void SetRowSpacing(double);
	long GetColumnFormat();
	void SetColumnFormat(long);
	double GetColumnSpacing();
	void SetColumnSpacing(double);
	CDataColorCollection GetColors();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_BAR1_H__21A6CC87_9310_4E1F_868D_A52BE20F7016__INCLUDED_)
