// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "bar1.h"

// Dispatch interfaces referenced by this interface
#include "DataColorCollection.h"


/////////////////////////////////////////////////////////////////////////////
// CBar1 properties

LPDISPATCH CBar1::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

long CBar1::GetRowFormat()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CBar1::SetRowFormat(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

double CBar1::GetRowSpacing()
{
	double result;
	GetProperty(0x3, VT_R8, (void*)&result);
	return result;
}

void CBar1::SetRowSpacing(double propVal)
{
	SetProperty(0x3, VT_R8, propVal);
}

long CBar1::GetColumnFormat()
{
	long result;
	GetProperty(0x4, VT_I4, (void*)&result);
	return result;
}

void CBar1::SetColumnFormat(long propVal)
{
	SetProperty(0x4, VT_I4, propVal);
}

double CBar1::GetColumnSpacing()
{
	double result;
	GetProperty(0x5, VT_R8, (void*)&result);
	return result;
}

void CBar1::SetColumnSpacing(double propVal)
{
	SetProperty(0x5, VT_R8, propVal);
}

CDataColorCollection CBar1::GetColors()
{
	LPDISPATCH pDispatch;
	GetProperty(0x6, VT_DISPATCH, (void*)&pDispatch);
	return CDataColorCollection(pDispatch);
}

/////////////////////////////////////////////////////////////////////////////
// CBar1 operations
