#if !defined(AFX_CHARTGROUPCOLLECTION1_H__B155D974_4886_437C_86EF_2F037909D567__INCLUDED_)
#define AFX_CHARTGROUPCOLLECTION1_H__B155D974_4886_437C_86EF_2F037909D567__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CChartGroup1;

/////////////////////////////////////////////////////////////////////////////
// CChartGroupCollection1 wrapper class

class CChartGroupCollection1 : public COleDispatchDriver
{
public:
	CChartGroupCollection1() {}		// Calls COleDispatchDriver default constructor
	CChartGroupCollection1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CChartGroupCollection1(const CChartGroupCollection1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	long GetCount();

// Operations
public:
	CChartGroup1 GetItem(const VARIANT& Index);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHARTGROUPCOLLECTION1_H__B155D974_4886_437C_86EF_2F037909D567__INCLUDED_)
