#if !defined(AFX_CHARTAREA1_H__D73BDEC5_5B9A_47F9_877F_20BA8475389B__INCLUDED_)
#define AFX_CHARTAREA1_H__D73BDEC5_5B9A_47F9_877F_20BA8475389B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CBorder1;
class CLocation1;
class CInterior1;
class CViewport;
class CPlotCube;
class CAxisCollection1;
class CView3D1;
class CSurface;
class CBar1;

/////////////////////////////////////////////////////////////////////////////
// CChartArea1 wrapper class

class CChartArea1 : public COleDispatchDriver
{
public:
	CChartArea1() {}		// Calls COleDispatchDriver default constructor
	CChartArea1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CChartArea1(const CChartArea1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	CBorder1 GetBorder();
	CLocation1 GetLocation();
	CInterior1 GetInterior();
	LPDISPATCH GetParent();
	CViewport GetViewport();
	CPlotCube GetPlotCube();
	CAxisCollection1 GetAxes();
	CView3D1 GetView3D();
	CSurface GetSurface();
	CBar1 GetBar();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHARTAREA1_H__D73BDEC5_5B9A_47F9_877F_20BA8475389B__INCLUDED_)
