#if !defined(AFX_CHART3DCOORDRESULT_H__3525002E_D638_48CB_BE01_28C81A71324B__INCLUDED_)
#define AFX_CHART3DCOORDRESULT_H__3525002E_D638_48CB_BE01_28C81A71324B__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CChart3DCoordResult wrapper class

class CChart3DCoordResult : public COleDispatchDriver
{
public:
	CChart3DCoordResult() {}		// Calls COleDispatchDriver default constructor
	CChart3DCoordResult(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CChart3DCoordResult(const CChart3DCoordResult& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	long GetX();
	void SetX(long);
	long GetY();
	void SetY(long);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHART3DCOORDRESULT_H__3525002E_D638_48CB_BE01_28C81A71324B__INCLUDED_)
