#if !defined(AFX_CHARTGROUP1_H__CB77BD60_39BF_4A8B_890A_4D53A7CB39CD__INCLUDED_)
#define AFX_CHARTGROUP1_H__CB77BD60_39BF_4A8B_890A_4D53A7CB39CD__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CElevation;
class CContour;
class CChart3DData;
class CLabelCollection1;
class CChart3DDataCoordResult;
class CChart3DCoordResult;
class CChart3DDataIndexResult;

/////////////////////////////////////////////////////////////////////////////
// CChartGroup1 wrapper class

class CChartGroup1 : public COleDispatchDriver
{
public:
	CChartGroup1() {}		// Calls COleDispatchDriver default constructor
	CChartGroup1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CChartGroup1(const CChartGroup1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	long GetChartType();
	void SetChartType(long);
	CElevation GetElevation();
	CContour GetContour();
	CChart3DData GetElevationData();
	void SetElevationData(LPDISPATCH);
	CChart3DData GetContourData();
	void SetContourData(LPDISPATCH);
	CLabelCollection1 GetColumnLabels();
	CLabelCollection1 GetRowLabels();

// Operations
public:
	long CoordToDataCoord(long XPixel, long YPixel, double* x, double* y, double* Z);
	void DataCoordToCoord(double x, double y, double Z, long* XPixel, long* YPixel);
	long CoordToDataIndex(long XPixel, long YPixel, long* Row, long* Column, long* Distance);
	void DataIndexToCoord(long Row, long Column, long* XPixel, long* YPixel);
	double DragZValue(long Row, long Column, long XPixel, long YPixel);
	double SurfaceValue(double x, double y);
	CChart3DDataCoordResult CoordToDataCoordObject(long XPixel, long YPixel);
	CChart3DCoordResult DataCoordToCoordObject(double x, double y, double Z);
	CChart3DDataIndexResult CoordToDataIndexObject(long XPixel, long YPixel);
	CChart3DCoordResult DataIndexToCoordObject(long Row, long Column);
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHARTGROUP1_H__CB77BD60_39BF_4A8B_890A_4D53A7CB39CD__INCLUDED_)
