#if !defined(AFX_CHARTLABELCOLLECTION1_H__4A953D55_C396_412E_8D85_94483F6EB8E4__INCLUDED_)
#define AFX_CHARTLABELCOLLECTION1_H__4A953D55_C396_412E_8D85_94483F6EB8E4__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CChartLabel1;

/////////////////////////////////////////////////////////////////////////////
// CChartLabelCollection1 wrapper class

class CChartLabelCollection1 : public COleDispatchDriver
{
public:
	CChartLabelCollection1() {}		// Calls COleDispatchDriver default constructor
	CChartLabelCollection1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CChartLabelCollection1(const CChartLabelCollection1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	long GetCount();

// Operations
public:
	CChartLabel1 Add();
	void Remove(const VARIANT& Index);
	CChartLabel1 GetItem(const VARIANT& Index);
	void RemoveAll();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_CHARTLABELCOLLECTION1_H__4A953D55_C396_412E_8D85_94483F6EB8E4__INCLUDED_)
