// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "coord1.h"


/////////////////////////////////////////////////////////////////////////////
// CCoord1 properties

LPDISPATCH CCoord1::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

long CCoord1::GetX()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CCoord1::SetX(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

long CCoord1::GetY()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CCoord1::SetY(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CCoord1 operations
