// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "dataindex1.h"


/////////////////////////////////////////////////////////////////////////////
// CDataIndex1 properties

LPDISPATCH CDataIndex1::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

long CDataIndex1::GetRow()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CDataIndex1::SetRow(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

long CDataIndex1::GetColumn()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CDataIndex1::SetColumn(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CDataIndex1 operations
