#if !defined(AFX_DATACOORD_H__ED0541C9_8321_4EE4_98B5_CAEE1F204A23__INCLUDED_)
#define AFX_DATACOORD_H__ED0541C9_8321_4EE4_98B5_CAEE1F204A23__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDataCoord wrapper class

class CDataCoord : public COleDispatchDriver
{
public:
	CDataCoord() {}		// Calls COleDispatchDriver default constructor
	CDataCoord(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDataCoord(const CDataCoord& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	double GetX();
	void SetX(double);
	double GetY();
	void SetY(double);
	long GetChartGroup();
	void SetChartGroup(long);
	LPDISPATCH GetParent();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DATACOORD_H__ED0541C9_8321_4EE4_98B5_CAEE1F204A23__INCLUDED_)
