#if !defined(AFX_DATACOLOR_H__251AEF50_48F7_487F_9098_781947FD8D82__INCLUDED_)
#define AFX_DATACOLOR_H__251AEF50_48F7_487F_9098_781947FD8D82__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CDataIndex1;

/////////////////////////////////////////////////////////////////////////////
// CDataColor wrapper class

class CDataColor : public COleDispatchDriver
{
public:
	CDataColor() {}		// Calls COleDispatchDriver default constructor
	CDataColor(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDataColor(const CDataColor& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	unsigned long GetColor();
	void SetColor(unsigned long);
	CDataIndex1 GetDataIndex();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DATACOLOR_H__251AEF50_48F7_487F_9098_781947FD8D82__INCLUDED_)
