#if !defined(AFX_DATACOLORCOLLECTION_H__237B0A0B_46D0_49B0_BE4E_1D0F69AC7FC5__INCLUDED_)
#define AFX_DATACOLORCOLLECTION_H__237B0A0B_46D0_49B0_BE4E_1D0F69AC7FC5__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CDataColor;

/////////////////////////////////////////////////////////////////////////////
// CDataColorCollection wrapper class

class CDataColorCollection : public COleDispatchDriver
{
public:
	CDataColorCollection() {}		// Calls COleDispatchDriver default constructor
	CDataColorCollection(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDataColorCollection(const CDataColorCollection& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	long GetCount();

// Operations
public:
	void Remove(const VARIANT& Row, const VARIANT& Column);
	CDataColor Add(const VARIANT& Row, const VARIANT& Column, unsigned long Color);
	CDataColor GetItem(const VARIANT& Row, const VARIANT& Column);
	void RemoveAll();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DATACOLORCOLLECTION_H__237B0A0B_46D0_49B0_BE4E_1D0F69AC7FC5__INCLUDED_)
