// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "deriveddouble1.h"


/////////////////////////////////////////////////////////////////////////////
// CDerivedDouble1 properties

LPDISPATCH CDerivedDouble1::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

BOOL CDerivedDouble1::GetIsDefault()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CDerivedDouble1::SetIsDefault(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

double CDerivedDouble1::GetValue()
{
	double result;
	GetProperty(0x3, VT_R8, (void*)&result);
	return result;
}

void CDerivedDouble1::SetValue(double propVal)
{
	SetProperty(0x3, VT_R8, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CDerivedDouble1 operations
