#if !defined(AFX_DERIVEDDOUBLE1_H__8DD0AB32_02C6_4491_A776_CF0E03A27506__INCLUDED_)
#define AFX_DERIVEDDOUBLE1_H__8DD0AB32_02C6_4491_A776_CF0E03A27506__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CDerivedDouble1 wrapper class

class CDerivedDouble1 : public COleDispatchDriver
{
public:
	CDerivedDouble1() {}		// Calls COleDispatchDriver default constructor
	CDerivedDouble1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CDerivedDouble1(const CDerivedDouble1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	BOOL GetIsDefault();
	void SetIsDefault(BOOL);
	double GetValue();
	void SetValue(double);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_DERIVEDDOUBLE1_H__8DD0AB32_02C6_4491_A776_CF0E03A27506__INCLUDED_)
