// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "elevation.h"


/////////////////////////////////////////////////////////////////////////////
// CElevation properties

LPDISPATCH CElevation::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

BOOL CElevation::GetIsMeshed()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CElevation::SetIsMeshed(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL CElevation::GetIsShaded()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CElevation::SetIsShaded(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

BOOL CElevation::GetIsTransparent()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CElevation::SetIsTransparent(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

unsigned long CElevation::GetMeshTopColor()
{
	unsigned long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CElevation::SetMeshTopColor(unsigned long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

unsigned long CElevation::GetMeshBottomColor()
{
	unsigned long result;
	GetProperty(0x6, VT_I4, (void*)&result);
	return result;
}

void CElevation::SetMeshBottomColor(unsigned long propVal)
{
	SetProperty(0x6, VT_I4, propVal);
}

unsigned long CElevation::GetShadedTopColor()
{
	unsigned long result;
	GetProperty(0x7, VT_I4, (void*)&result);
	return result;
}

void CElevation::SetShadedTopColor(unsigned long propVal)
{
	SetProperty(0x7, VT_I4, propVal);
}

unsigned long CElevation::GetShadedBottomColor()
{
	unsigned long result;
	GetProperty(0x8, VT_I4, (void*)&result);
	return result;
}

void CElevation::SetShadedBottomColor(unsigned long propVal)
{
	SetProperty(0x8, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CElevation operations
