#if !defined(AFX_ELEVATION_H__D2EF3F55_D430_4CAA_9A94_C792DBFB6BAD__INCLUDED_)
#define AFX_ELEVATION_H__D2EF3F55_D430_4CAA_9A94_C792DBFB6BAD__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.

/////////////////////////////////////////////////////////////////////////////
// CElevation wrapper class

class CElevation : public COleDispatchDriver
{
public:
	CElevation() {}		// Calls COleDispatchDriver default constructor
	CElevation(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CElevation(const CElevation& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	BOOL GetIsMeshed();
	void SetIsMeshed(BOOL);
	BOOL GetIsShaded();
	void SetIsShaded(BOOL);
	BOOL GetIsTransparent();
	void SetIsTransparent(BOOL);
	unsigned long GetMeshTopColor();
	void SetMeshTopColor(unsigned long);
	unsigned long GetMeshBottomColor();
	void SetMeshBottomColor(unsigned long);
	unsigned long GetShadedTopColor();
	void SetShadedTopColor(unsigned long);
	unsigned long GetShadedBottomColor();
	void SetShadedBottomColor(unsigned long);

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_ELEVATION_H__D2EF3F55_D430_4CAA_9A94_C792DBFB6BAD__INCLUDED_)
