#if !defined(AFX_FLOOR_H__57E9AB1B_B8D9_409E_80DB_F81A742DFDD8__INCLUDED_)
#define AFX_FLOOR_H__57E9AB1B_B8D9_409E_80DB_F81A742DFDD8__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CProjection;

/////////////////////////////////////////////////////////////////////////////
// CFloor wrapper class

class CFloor : public COleDispatchDriver
{
public:
	CFloor() {}		// Calls COleDispatchDriver default constructor
	CFloor(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CFloor(const CFloor& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	CProjection GetProjection();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_FLOOR_H__57E9AB1B_B8D9_409E_80DB_F81A742DFDD8__INCLUDED_)
