// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "gridlines1.h"


/////////////////////////////////////////////////////////////////////////////
// CGridLines1 properties

LPDISPATCH CGridLines1::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

BOOL CGridLines1::GetIsOnXYPlane()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CGridLines1::SetIsOnXYPlane(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL CGridLines1::GetIsOnXZPlane()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CGridLines1::SetIsOnXZPlane(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

BOOL CGridLines1::GetIsOnYZPlane()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CGridLines1::SetIsOnYZPlane(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CGridLines1 operations
