// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "interior1.h"

// Dispatch interfaces referenced by this interface
#include "image1.h"


/////////////////////////////////////////////////////////////////////////////
// CInterior1 properties

LPDISPATCH CInterior1::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

unsigned long CInterior1::GetBackgroundColor()
{
	unsigned long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CInterior1::SetBackgroundColor(unsigned long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

unsigned long CInterior1::GetForegroundColor()
{
	unsigned long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CInterior1::SetForegroundColor(unsigned long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

CImage1 CInterior1::GetImage()
{
	LPDISPATCH pDispatch;
	GetProperty(0x4, VT_DISPATCH, (void*)&pDispatch);
	return CImage1(pDispatch);
}

/////////////////////////////////////////////////////////////////////////////
// CInterior1 operations
