#if !defined(AFX_LABELCOLLECTION1_H__1A36F539_8D47_4A64_B754_9E9919D03E02__INCLUDED_)
#define AFX_LABELCOLLECTION1_H__1A36F539_8D47_4A64_B754_9E9919D03E02__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CLabel1;

/////////////////////////////////////////////////////////////////////////////
// CLabelCollection1 wrapper class

class CLabelCollection1 : public COleDispatchDriver
{
public:
	CLabelCollection1() {}		// Calls COleDispatchDriver default constructor
	CLabelCollection1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLabelCollection1(const CLabelCollection1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	long GetCount();

// Operations
public:
	CLabel1 Add(LPCTSTR Text, const VARIANT& Before);
	void Remove(const VARIANT& Index);
	CLabel1 GetItem(const VARIANT& Index);
	void RemoveAll();
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LABELCOLLECTION1_H__1A36F539_8D47_4A64_B754_9E9919D03E02__INCLUDED_)
