#if !defined(AFX_LEGEND1_H__7F3CDA55_B6E0_4E1A_9EDB_79B1AB7207D2__INCLUDED_)
#define AFX_LEGEND1_H__7F3CDA55_B6E0_4E1A_9EDB_79B1AB7207D2__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000
// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


// Dispatch interfaces referenced by this interface
class CBorder1;
class CLocation1;
class CInterior1;
class COleFont;
class CLabelCollection1;

/////////////////////////////////////////////////////////////////////////////
// CLegend1 wrapper class

class CLegend1 : public COleDispatchDriver
{
public:
	CLegend1() {}		// Calls COleDispatchDriver default constructor
	CLegend1(LPDISPATCH pDispatch) : COleDispatchDriver(pDispatch) {}
	CLegend1(const CLegend1& dispatchSrc) : COleDispatchDriver(dispatchSrc) {}

// Attributes
public:
	LPDISPATCH GetParent();
	long GetAnchor();
	void SetAnchor(long);
	long GetOrientation();
	void SetOrientation(long);
	BOOL GetIsShowing();
	void SetIsShowing(BOOL);
	CBorder1 GetBorder();
	CLocation1 GetLocation();
	CInterior1 GetInterior();
	long GetType();
	void SetType(long);
	COleFont GetFont();
	void SetFont(LPDISPATCH);
	CLabelCollection1 GetLabels();

// Operations
public:
};

//{{AFX_INSERT_LOCATION}}
// Microsoft Visual C++ will insert additional declarations immediately before the previous line.

#endif // !defined(AFX_LEGEND1_H__7F3CDA55_B6E0_4E1A_9EDB_79B1AB7207D2__INCLUDED_)
