//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by wet_h.rc
//
#define ID_MODELANALYSIS_CALCKEVINDIST  0
#define IDCANCEL2                       3
#define IDD_ABOUTBOX                    100
#define IDD_PPUSERINTERACTIONPESTICIDE  103
#define IDD_PROPPAGE_MODELINTERACTION   106
#define IDR_MAINFRAME                   128
#define IDR_WET_HTYPE                   129
#define IDR_MAPCONTEXTMENU              134
#define IDD_CELLPROPERTIES              135
#define IDD_CELLPROPERTIES1             136
#define IDD_MAPLAYERPROPS               137
#define IDD_ClassifyLayerDlg            138
#define IDD_SAVERESULTS                 140
#define IDB_CHECK                       145
#define IDD_OPTIMIZE                    146
#define IDD_3DCHART                     153
#define IDD_DIALOG1                     155
#define IDD_RAINFALLPLOT                158
#define IDD_ETPARAMPMDLG                162
#define IDD_ETPARAMHARDLG               163
#define IDD_MAPSTATS                    166
#define IDD_PROPPAGE_INTERFACEINTERACTION 167
#define IDD_PROPPAGE_MODELSTRUCTURE     168
#define IDD_PROPPAGE_                   169
#define IDD_PROPPAGE_TRACERINTERACTION  169
#define IDD_PROPPAGE_SIMULATIONCONTROL  170
#define IDD_PROPPAGE_SEDIMENT           171
#define IDD_PROPPAGE_ET                 172
#define IDD_PROPPAGE_LANDUSECHANGE      173
#define IDD_PROPPAGE_FLOWMOD            176
#define IDD_MCPARAM                     177
#define IDD_DIALOGUNIFPARAM             178
#define IDD_LOGNORMPARAM                179
#define IDD_PROPPAGE_VERTICAL           180
#define IDD_PROPPAGE_HORIZONTAL         181
#define IDD_PROPPAGE_CHANNEL            182
#define ID_MODELANALYSIS_DEFINEHYDROLOGYMODEL 183
#define IDD_PROPPAGE_PARAMETERVALUES    183
#define IDD_PROPPAGE_EVALUATION         184
#define ID_MODELANALYSIS_MODELEVALUATION 184
#define ID_MODELANALYSIS_PESTICIDEMODEL 185
#define ID_MODELANALYSIS_TRACERMODEL    186
#define ID_MODELANALYSIS_RESTORESIMULATIONS 187
#define ID_EXTENSIONS_LANDUSECHANGESENSITIVITY 188
#define ID_MODELANALYSIS_RESTORATIONSENSITIVITY 189
#define IDC_LAYERNAME                   1000
#define IDC_FILE                        1001
#define IDC_TYPE                        1002
#define IDC_FEATURES                    1003
#define IDC_VISIBLE                     1004
#define IDC_SHOWOUTLINES                1005
#define IDC_SLIDER1                     1006
#define IDC_OUTLINECOLOR                1007
#define IDC_FLASHCELL                   1008
#define IDC_PREVCELL                    1009
#define IDC_NEXTCELL                    1010
#define IDC_INTENSITY                   1011
#define IDC_STARTTIME                   1011
#define IDC_INTENSITYTEXT               1012
#define IDC_IDOK                        1012
#define IDC_LIGHTER                     1013
#define IDC_DARKER                      1014
#define IDC_MINM                        1014
#define IDC_MAXM                        1015
#define IDC_M                           1016
#define IDC_MINIS                       1017
#define IDC_MMAX                        1017
#define IDC_MAXIS                       1018
#define IDC_IS                          1019
#define IDC_MINN                        1020
#define IDC_QINIT                       1020
#define IDC_LTPRECIP                    1020
#define IDC_ISMAX                       1020
#define IDC_MAXN                        1021
#define IDC_N                           1022
#define IDC_MINKS                       1023
#define IDC_NMAX                        1023
#define IDC_MAXKS                       1024
#define IDC_KS                          1025
#define IDC_CHECKIPS                    1026
#define IDC_CHECKN                      1027
#define IDC_CHECKKSAT                   1028
#define IDC_OPTLENGTH                   1029
#define IDC_CHECKUPSLOPE                1029
#define IDC_OPTTIMESTEP                 1030
#define IDC_CHECKKDEPTH                 1030
#define IDC_OPTTIME                     1031
#define IDC_CHECKPOROSITY               1031
#define IDC_ICLENGTH                    1032
#define IDC_OPTIMIZE                    1033
#define IDC_LAMDA                       1033
#define IDC_OPTTIME2                    1034
#define IDC_LAMDAFACTOR                 1035
#define IDC_OPTTIME3                    1036
#define IDC_OPT                         1037
#define IDC_MINSOILDEPTH                1038
#define IDC_MAXSOILDEPTH                1039
#define IDC_SOILDEPTH                   1040
#define IDC_CHECKSOILDEPTH              1041
#define IDC_RUN                         1042
#define IDC_MINKDEPTH                   1043
#define IDC_MAXKDEPTH                   1044
#define IDC_KDEPTH                      1045
#define IDC_CHECKKDDEPTH                1046
#define IDC_OTHEROUTPUT                 1047
#define IDC_MINET                       1048
#define IDC_MAXET                       1049
#define ID_SELECT                       1050
#define IDC_ET                          1050
#define ID_ZOOMIN                       1051
#define IDC_CHECKET                     1051
#define ID_ZOOMOUT                      1052
#define IDC_PERTURBPERCENT              1052
#define ID_ZOOMFULL                     1053
#define ID_PAN                          1054
#define IDC_PROGRESSBOX                 1054
#define ID_QUERYDISTANCE                1055
#define ID_DBTABLE                      1056
#define ID_ANALYSIS_RUNMODEL            1057
#define IDC_2DCHART                     1057
#define IDC_CHECKSIMULATIONSTUDY        1059
#define IDC_CELLLIST                    1060
#define IDC_SELECTALLCELLS              1061
#define IDC_3DCHART                     1061
#define IDC_REMOVECELLS                 1062
#define IDC_REACHLIST                   1063
#define IDC_SELECTALLREACHES            1064
#define IDC_REMOVEREACHES               1065
#define IDC_TIMESTEP                    1066
#define IDC_STOPTIME                    1067
#define IDC_RUNMODEL                    1068
#define IDC_RUNSYNTHETIC                1068
#define IDC_SAMPLECELLS                 1069
#define IDC_SAMPLEREACHES               1070
#define IDC_ADDROOTREACH                1071
#define IDC_VARIABLESTEP                1072
#define IDC_MODELSTARTTIME              1073
#define IDC_CHECK1                      1074
#define IDC_CHECKM                      1074
#define IDC_DELTAX                      1074
#define IDC_CHECKRIPARIAN               1074
#define IDC_VARIABLETIMESTEP            1074
#define IDC_CHECKCL                     1074
#define IDC_CHECKSIMET                  1074
#define IDC_CHECKINSTREAMSEDIMENT       1074
#define IDC_CHECKMODELWETLANDS          1074
#define IDC_SAVEEMFOUT                  1074
#define IDC_CHECKINCRFLOW               1074
#define IDC_CHECKPESTICIDE              1074
#define IDC_CHECKUNSATURATED            1074
#define IDC_WDRATIO                     1075
#define IDC_CHECKTILEDRAINAGE           1075
#define IDC_CHECKINSTREAM               1075
#define IDC_CHECKROUTEINSTREAM          1075
#define IDC_CHECKUPLANDSEDIMENT         1075
#define IDC_CHECKIS                     1075
#define IDC_CHECK3                      1075
#define IDC_CHECKUPDATESTREAM           1076
#define IDC_CHECK4                      1076
#define IDC_KSAT                        1077
#define IDC_CHECKUPDATEUPLAND           1077
#define IDC_CHECK5                      1077
#define IDC_MINQ                        1078
#define IDC_KSATMAX                     1078
#define IDC_CHECK6                      1078
#define IDC_MAXQ                        1079
#define IDC_UPSLOPEMAX                  1079
#define IDC_CHECK7                      1079
#define IDC_NUMBIN                      1080
#define IDC_RADIOWATERSHED              1080
#define IDC_CHECK8                      1080
#define IDC_WIDTHLINE                   1081
#define IDC_RADIOCELL                   1081
#define IDC_CHECK9                      1081
#define IDC_COLLECTIONINT               1082
#define IDC_RADIODISTIBUTE              1082
#define IDC_CHECK24                     1082
#define IDC_UPMIN                       1083
#define IDC_CHECK25                     1083
#define IDC_UPMAX                       1084
#define IDC_CHECK26                     1084
#define IDC_UPNUMBIN                    1085
#define IDC_CHECK27                     1085
#define IDC_RADIOSWC                    1086
#define IDC_RADIODEGSAT                 1087
#define IDC_RADIODEPSAT                 1088
#define IDC_RADIOET                     1089
#define IDC_RADIOQ                      1090
#define IDC_RADIOVEL                    1091
#define IDC_RADIODEP                    1092
#define IDC_RADIOCEL                    1093
#define IDC_RADIOWID                    1094
#define IDC_HATCHCOLOR                  1095
#define IDC_CHECKUPDATECLASSEXTENT      1095
#define IDC_COLLECTIONINT2              1096
#define IDC_DISTBAND                    1097
#define IDC_NUMBANDS                    1098
#define IDC_KSATASPARAM                 1098
#define IDC_SDASPARAM                   1099
#define IDC_RAINFALLCHART               1100
#define IDC_CHECKPRISM                  1100
#define IDC_CHECKUSESOILLIST            1101
#define IDC_MODELSTOPTIME               1107
#define IDC_INITIALTIMESTEP             1108
#define IDC_MINIMUMTIMESTEP             1109
#define IDC_MAXIMUMTIMESTEP             1110
#define IDC_ERRORTOLERANCE              1111
#define IDC_RADIOCENTROID               1113
#define IDC_RADIOBUFFER                 1114
#define IDC_RADIOCLTIME                 1116
#define IDC_RADIOCLCONSTANT             1117
#define IDC_EDITCLMGL                   1118
#define IDC_RADIOCLTIME2                1119
#define IDC_RADIO1                      1119
#define IDC_RADIOHAR                    1119
#define IDC_EDITINITSOILCONC            1119
#define IDC_RADIOCLCONSTANT2            1120
#define IDC_RADIO2                      1120
#define IDC_RADIOPM                     1120
#define IDC_EDITCLMGL2                  1121
#define IDC_RADIOPENMAN                 1121
#define IDC_RADIO3                      1121
#define IDC_RADIO4                      1122
#define IDC_CHECKSIDEOFSTREAM           1122
#define IDC_BUTTONVIEWPARAM             1123
#define IDC_RADIO5                      1123
#define IDC_EDIT1                       1124
#define IDC_ETR                         1125
#define IDC_CHECKREDUCESEDIMENT         1125
#define IDC_EDITTILEOUTFLOW             1125
#define IDC_EDIT2                       1125
#define IDC_FRRADCLOUD                  1126
#define IDC_REDUCESEDIMENTPER           1126
#define IDC_EDIT3                       1126
#define IDC_FRARACLEAR                  1127
#define IDC_BUTTONRECALC                1127
#define IDC_KSATDIST                    1127
#define IDC_HOURBRIGHT                  1128
#define IDC_UPSLOPEDIST                 1128
#define IDC_HOURDAY                     1129
#define IDC_PHI                         1129
#define IDC_INCSHORT                    1130
#define IDC_LHE                         1132
#define IDC_AC                          1133
#define IDC_BC                          1134
#define IDC_SPINBUTTON                  1134
#define IDC_SBC                         1135
#define IDC_APPLYSEDOPTIONS             1135
#define IDC_GRADSATVAPP                 1136
#define IDC_CHECKROUTECHANNEL           1136
#define IDC_PSYCH                       1137
#define IDC_CHECKROUTECHANSOLUTES       1137
#define IDC_AIRDEN                      1138
#define IDC_EDITBUFFERWIDTH             1138
#define IDC_SPEHEAT                     1139
#define IDC_CONTROL1                    1139
#define IDC_SATVAPP                     1140
#define IDC_STOREDE                     1147
#define IDC_TOTALAREA                   1148
#define IDC_BIOGEOABS                   1148
#define IDC_RESTOREDAREA                1149
#define IDC_HEATCOND                    1149
#define IDC_TOTALCELLS                  1150
#define IDC_HEIGHTHUM                   1150
#define IDC_RESTOREDCELLS               1151
#define IDC_WINDSPEED                   1151
#define IDC_HEIGHTWIND                  1152
#define IDC_DATETIMEPICKERBEGIN         1155
#define IDC_RH                          1156
#define IDC_DATETIMEPICKEREND           1156
#define IDC_EDITPERINCREASE             1157
#define IDC_CHECKMODELTILEDRAINS        1160
#define IDC_EDITTILETHRESH              1161
#define IDC_CHECKMONTE                  1164
#define IDC_EDITNUMITERAT               1165
#define IDC_EDITRANDSEED                1166
#define IDC_BUTTONMCADDITIONAL          1166
#define IDC_SPIN5                       1170
#define IDC_SPIN6                       1171
#define IDC_SPIN7                       1172
#define IDC_SPIN8                       1173
#define IDC_NMIN                        1174
#define IDC_NDIST                       1175
#define IDC_ISMIN                       1176
#define IDC_MMIN                        1178
#define IDC_MDIST                       1179
#define IDC_KSATMIN                     1180
#define IDC_UPSLOPEMIN                  1181
#define IDC_SPIN9                       1182
#define IDC_COMBON                      1184
#define IDC_COMBOIS                     1185
#define IDC_SPIN2                       1186
#define IDC_COMBOM                      1187
#define IDC_SPIN3                       1188
#define IDC_COMBOKSAT                   1189
#define IDC_SPIN4                       1190
#define IDC_COMBOUP                     1191
#define IDC_BUTTONN                     1192
#define IDC_BUTTONIS                    1193
#define IDC_CHECKTHREEGAGES             1193
#define IDC_BUTTONM                     1194
#define IDC_BUTTON1                     1194
#define IDC_BUTTONK                     1195
#define IDC_EDITPESTAPPDATA             1195
#define IDC_BUTTONU                     1196
#define IDC_COMBOKDEPTH                 1197
#define IDC_BUTTONKDEPTH                1198
#define IDC_LISTCHEMICAL                1198
#define IDC_COMBOPOROSITY               1199
#define IDC_BUTTONPOROSITY              1200
#define IDC_BUTTON2                     1200
#define IDC_EDITPARAM                   1200
#define IDC_EDITAPP                     1202
#define IDC_EDITNUMBANDS                1202
#define IDC_RADIOVANGEN                 1204
#define IDC_CHECKPARAMM                 1204
#define IDC_RADIOSSEIMC                 1205
#define IDC_CHECKSTUC                   1205
#define IDC_CHECKSTRUC                  1205
#define IDC_CHECKEQUATION               1206
#define IDC_RADIOSSEIMC2                1206
#define IDC_RADIOSPOWERLAW              1206
#define IDC_CHECKPARAMKD                1207
#define IDC_LIST1                       1208
#define IDC_CHECKPARAMINIT              1208
#define IDC_CHECKPARAMVAN               1209
#define IDC_CHECKPARAMWD                1210
#define IDC_CHECKPARAMPHI               1211
#define IDC_STATIC3                     1212
#define IDC_CHECKPARAMZ                 1212
#define IDC_CHECKUNSAT                  1213
#define IDC_CHECKPARAMK1                1213
#define IDC_CHECKINTERCEPTION           1214
#define IDC_CHECKPARAMK2                1214
#define IDC_RADIOHARGREAVES             1215
#define IDC_CHECKPARAMFC                1215
#define IDC_RADIOPEN                    1216
#define IDC_CHECKPARAMN                 1216
#define IDC_RADIOPENMON                 1217
#define IDC_CHECKPARAMKSAT              1217
#define IDC_RADIOMEAS                   1218
#define IDC_CHECKPARAMWP                1218
#define IDC_RADIOUSEIMC                 1219
#define IDC_RADIOSEIMC                  1219
#define IDC_RADIOSTOPMODEL              1220
#define IDC_RADIO9                      1221
#define IDC_RADIO10                     1222
#define IDC_RADIO11                     1223
#define IDC_RADIO12                     1224
#define IDC_RADIO13                     1225
#define IDC_RADIOSEMI                   1225
#define IDC_RADIO14                     1226
#define IDC_RADIOHILLRIP                1226
#define IDC_RADIO15                     1227
#define IDC_RADIOCENT                   1227
#define IDC_RADIO16                     1228
#define IDC_RADIOBUFF                   1228
#define IDC_EDITNUMITER                 1239
#define IDC_RADIOMONTE                  1240
#define IDC_STATICNUMITER               1241
#define IDC_STATICNUMBANDS              1242
#define IDC_REREADPARAM                 1243
#define IDC_RADIOGEOMOR                 1244
#define IDC_RADIOLUMPED                 1245
#define IDC_RADIOFPGRID                 1246
#define IDC_CHECKTRACERSOURCE           1247
#define IDC_RADIOWTHEIGHT               1247
#define IDC_LISTCHOSENCELLS             1248
#define IDC_CHECK2                      1250
#define IDC_CHECKPLE2                   1250
#define IDC_RADIOPOROSITYCON            1252
#define IDC_RADIOPOROSITYEXP            1253
#define IDC_CHECKSNOW                   1254
#define IDC_CHECKGRIDMET                1255
#define ID_CELLPROPERTIES               32773
#define ID_CLEARALTERNATIVES            32774
#define ID_SELECTWATERSHED              32775
#define ID_RECLASSIFYDATA               32776
#define ID_FILE_LOADCLIMATE             32778
#define ID_STATISTICS                   32779
#define ID_PROCESSCELL_GO               32780
#define ID_MODELANALYSIS_USERINTERACTION 32781
#define ID_MODELANALYSIS_EDITTABULARDATA 32783
#define ID_SHOWRESULTS                  32784
#define ID_MODELANALYSIS_RUNMODEL       32784
#define IDC_COLORRAMP                   32785
#define ID_MODELANALYSIS_GENERATEREPORT 32785
#define IDC_DATAFIELD                   32786
#define ID_FILE_SAVEPARAMETERS          32786
#define IDC_BINCOUNT                    32787
#define IDC_SPIN1                       32788
#define ID_APP_STOP                     32788
#define IDC_UNIQUEVALUES                32789
#define ID_BUTTON32789                  32789
#define ID_CALCFPDIST                   32789
#define IDC_GENERATEBINS                32790
#define IDC_BINLIST                     32791
#define ID_APP_MODELDEFINITION          32791
#define IDC_FIELDTYPE                   32792
#define ID_TOPOGRAPHICCALCULATION_MEANWATERSHEDELEVATION 32792
#define ID_TOPOGRAPHICCALCULATION_SUBBASINFPDISTRIBUTION 32793
#define ID_TOPOGRAPHICCALCULATION_SUBBASINDISTANCETODSOUTLETDISTRIBUTION 32794
#define ID_TOPOGRAPHICCALCULATION_DISTANCEFROMPOLYTOSTREAM 32795
#define ID_TOPOGRAPHICCALCULATION_CALCULATEUPSTREAMAREA 32796
#define ID_ADDITIONALSTUFF_LOADUARADAR  32799
#define ID_TOPOGRAPHICCALCULATION_SIDEOFSTREAM 32800
#define ID_MODELANALYSIS_SAVEMODELSTATE 32801
#define ID_TOPOGRAPHICCALCULATION_DISTTOSTREAM 32802
#define ID_Menu                         32803
#define ID_MODELANALYSIS_RUNHILLSLOPEMODEL 32804
#define ID_TOPOGRAPHICCALCULATION_WILLAMETTEQMOVIE 32805
#define ID_TOPOGRAPHICCALCULATION_DISGRADIENTANDQUOTIENTFORGRID 32806

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        191
#define _APS_NEXT_COMMAND_VALUE         32807
#define _APS_NEXT_CONTROL_VALUE         1255
#define _APS_NEXT_SYMED_VALUE           105
#endif
#endif
