// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "strokefont.h"


/////////////////////////////////////////////////////////////////////////////
// CStrokeFont properties

LPDISPATCH CStrokeFont::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

long CStrokeFont::GetType()
{
	long result;
	GetProperty(0x2, VT_I4, (void*)&result);
	return result;
}

void CStrokeFont::SetType(long propVal)
{
	SetProperty(0x2, VT_I4, propVal);
}

long CStrokeFont::GetSize()
{
	long result;
	GetProperty(0x3, VT_I4, (void*)&result);
	return result;
}

void CStrokeFont::SetSize(long propVal)
{
	SetProperty(0x3, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CStrokeFont operations
