// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "surface.h"


/////////////////////////////////////////////////////////////////////////////
// CSurface properties

LPDISPATCH CSurface::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

BOOL CSurface::GetIsSolid()
{
	BOOL result;
	GetProperty(0x2, VT_BOOL, (void*)&result);
	return result;
}

void CSurface::SetIsSolid(BOOL propVal)
{
	SetProperty(0x2, VT_BOOL, propVal);
}

BOOL CSurface::GetIsRowMeshShowing()
{
	BOOL result;
	GetProperty(0x3, VT_BOOL, (void*)&result);
	return result;
}

void CSurface::SetIsRowMeshShowing(BOOL propVal)
{
	SetProperty(0x3, VT_BOOL, propVal);
}

BOOL CSurface::GetIsColumnMeshShowing()
{
	BOOL result;
	GetProperty(0x4, VT_BOOL, (void*)&result);
	return result;
}

void CSurface::SetIsColumnMeshShowing(BOOL propVal)
{
	SetProperty(0x4, VT_BOOL, propVal);
}

long CSurface::GetRowMeshFilter()
{
	long result;
	GetProperty(0x5, VT_I4, (void*)&result);
	return result;
}

void CSurface::SetRowMeshFilter(long propVal)
{
	SetProperty(0x5, VT_I4, propVal);
}

long CSurface::GetColumnMeshFilter()
{
	long result;
	GetProperty(0x6, VT_I4, (void*)&result);
	return result;
}

void CSurface::SetColumnMeshFilter(long propVal)
{
	SetProperty(0x6, VT_I4, propVal);
}

/////////////////////////////////////////////////////////////////////////////
// CSurface operations
