// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "valuelabel1.h"

// Dispatch interfaces referenced by this interface
#include "label1.h"


/////////////////////////////////////////////////////////////////////////////
// CValueLabel1 properties

LPDISPATCH CValueLabel1::GetParent()
{
	LPDISPATCH result;
	GetProperty(0x1, VT_DISPATCH, (void*)&result);
	return result;
}

double CValueLabel1::GetValue()
{
	double result;
	GetProperty(0x2, VT_R8, (void*)&result);
	return result;
}

void CValueLabel1::SetValue(double propVal)
{
	SetProperty(0x2, VT_R8, propVal);
}

CLabel1 CValueLabel1::GetLabel()
{
	LPDISPATCH pDispatch;
	GetProperty(0x3, VT_DISPATCH, (void*)&pDispatch);
	return CLabel1(pDispatch);
}

/////////////////////////////////////////////////////////////////////////////
// CValueLabel1 operations
